/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SevasRouteImport } from './routes/sevas'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as MySubscriptionRouteImport } from './routes/my-subscription'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PlanPlanIdRouteImport } from './routes/plan.$planId'
import { Route as CheckoutPlanIdRouteImport } from './routes/checkout.$planId'
import { Route as AdminSubscribersRouteImport } from './routes/admin.subscribers'
import { Route as AdminOverviewRouteImport } from './routes/admin.overview'

const SevasRoute = SevasRouteImport.update({
  id: '/sevas',
  path: '/sevas',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const MySubscriptionRoute = MySubscriptionRouteImport.update({
  id: '/my-subscription',
  path: '/my-subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PlanPlanIdRoute = PlanPlanIdRouteImport.update({
  id: '/plan/$planId',
  path: '/plan/$planId',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutPlanIdRoute = CheckoutPlanIdRouteImport.update({
  id: '/checkout/$planId',
  path: '/checkout/$planId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubscribersRoute = AdminSubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOverviewRoute = AdminOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/faq': typeof FaqRoute
  '/my-subscription': typeof MySubscriptionRoute
  '/plans': typeof PlansRoute
  '/profile': typeof ProfileRoute
  '/reviews': typeof ReviewsRoute
  '/sevas': typeof SevasRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/checkout/$planId': typeof CheckoutPlanIdRoute
  '/plan/$planId': typeof PlanPlanIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/my-subscription': typeof MySubscriptionRoute
  '/plans': typeof PlansRoute
  '/profile': typeof ProfileRoute
  '/reviews': typeof ReviewsRoute
  '/sevas': typeof SevasRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/checkout/$planId': typeof CheckoutPlanIdRoute
  '/plan/$planId': typeof PlanPlanIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/faq': typeof FaqRoute
  '/my-subscription': typeof MySubscriptionRoute
  '/plans': typeof PlansRoute
  '/profile': typeof ProfileRoute
  '/reviews': typeof ReviewsRoute
  '/sevas': typeof SevasRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/checkout/$planId': typeof CheckoutPlanIdRoute
  '/plan/$planId': typeof PlanPlanIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/faq'
    | '/my-subscription'
    | '/plans'
    | '/profile'
    | '/reviews'
    | '/sevas'
    | '/admin/overview'
    | '/admin/subscribers'
    | '/checkout/$planId'
    | '/plan/$planId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/faq'
    | '/my-subscription'
    | '/plans'
    | '/profile'
    | '/reviews'
    | '/sevas'
    | '/admin/overview'
    | '/admin/subscribers'
    | '/checkout/$planId'
    | '/plan/$planId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/faq'
    | '/my-subscription'
    | '/plans'
    | '/profile'
    | '/reviews'
    | '/sevas'
    | '/admin/overview'
    | '/admin/subscribers'
    | '/checkout/$planId'
    | '/plan/$planId'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  FaqRoute: typeof FaqRoute
  MySubscriptionRoute: typeof MySubscriptionRoute
  PlansRoute: typeof PlansRoute
  ProfileRoute: typeof ProfileRoute
  ReviewsRoute: typeof ReviewsRoute
  SevasRoute: typeof SevasRoute
  CheckoutPlanIdRoute: typeof CheckoutPlanIdRoute
  PlanPlanIdRoute: typeof PlanPlanIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sevas': {
      id: '/sevas'
      path: '/sevas'
      fullPath: '/sevas'
      preLoaderRoute: typeof SevasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-subscription': {
      id: '/my-subscription'
      path: '/my-subscription'
      fullPath: '/my-subscription'
      preLoaderRoute: typeof MySubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/plan/$planId': {
      id: '/plan/$planId'
      path: '/plan/$planId'
      fullPath: '/plan/$planId'
      preLoaderRoute: typeof PlanPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$planId': {
      id: '/checkout/$planId'
      path: '/checkout/$planId'
      fullPath: '/checkout/$planId'
      preLoaderRoute: typeof CheckoutPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subscribers': {
      id: '/admin/subscribers'
      path: '/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AdminSubscribersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/overview': {
      id: '/admin/overview'
      path: '/overview'
      fullPath: '/admin/overview'
      preLoaderRoute: typeof AdminOverviewRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminOverviewRoute: typeof AdminOverviewRoute
  AdminSubscribersRoute: typeof AdminSubscribersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminOverviewRoute: AdminOverviewRoute,
  AdminSubscribersRoute: AdminSubscribersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  FaqRoute: FaqRoute,
  MySubscriptionRoute: MySubscriptionRoute,
  PlansRoute: PlansRoute,
  ProfileRoute: ProfileRoute,
  ReviewsRoute: ReviewsRoute,
  SevasRoute: SevasRoute,
  CheckoutPlanIdRoute: CheckoutPlanIdRoute,
  PlanPlanIdRoute: PlanPlanIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
