-- =============================================================
-- PUNYATA — Session 6.5: Add 'owner' role to profiles.role CHECK
-- Project  : omjivlmfsikeqwndtlcn  (Supabase "Punyata")
-- Branch   : Staging
-- Depends  : 20260801_005_segment_video_revision.sql
-- Created  : 2026-08-01
-- =============================================================
--
-- PURPOSE:
--   Establishes the two-tier admin hierarchy:
--     OWNER = superset of admin + all financial visibility
--             (/admin/reports, MRR/revenue figures, payment
--             amounts, Razorpay IDs, agent commission).
--     ADMIN = full operational access, ZERO financial visibility.
--
-- WHAT THIS MIGRATION DOES (and ONLY this):
--   Replaces the CHECK constraint on public.profiles.role so the
--   allowed set becomes ('user','admin','owner','agent').
--
-- HARD CONSTRAINTS HONOURED HERE:
--   - All existing rows/values are preserved (CHECK replacement
--     validates existing rows — all current roles remain valid
--     under the new, wider set, so the ADD cannot fail on data).
--   - The existing 'agent' value is NOT touched or renamed.
--   - NO existing profile is auto-promoted to 'owner'. Promotion
--     is a manual, audited step (see commented example at bottom).
--
-- CONSTRAINT NAME DISCOVERY (do-not-assume rule):
--   The original CHECK was declared INLINE in migration
--   20260725_001 (column-level `CHECK (role IN (...))`), so its
--   name was auto-generated by Postgres (convention suggests
--   'profiles_role_check', but re-runs / restores / branch dbs can
--   differ). This migration therefore looks the name up in
--   pg_constraint at runtime and drops whatever CHECK currently
--   constrains the role column — it never assumes a name.
-- =============================================================


-- ─────────────────────────────────────────────────────────────
-- 1. Discover + drop the existing CHECK on profiles.role
-- ─────────────────────────────────────────────────────────────
-- conkey holds the attnums of columns the CHECK references; we
-- match any CHECK constraint on public.profiles that references
-- the 'role' column. RAISE NOTICE records what was found so the
-- migration log shows the exact (discovered) constraint name.

DO $$
DECLARE
    cname text;
BEGIN
    SELECT con.conname
      INTO cname
      FROM pg_constraint con
      JOIN pg_class rel       ON rel.oid = con.conrelid
      JOIN pg_namespace nsp   ON nsp.oid = rel.relnamespace
      JOIN pg_attribute att   ON att.attrelid = rel.oid
                             AND att.attnum = ANY (con.conkey)
     WHERE nsp.nspname  = 'public'
       AND rel.relname  = 'profiles'
       AND con.contype  = 'c'          -- CHECK constraint
       AND att.attname  = 'role'
     LIMIT 1;

    IF cname IS NOT NULL THEN
        RAISE NOTICE 'Dropping discovered CHECK constraint on profiles.role: %', cname;
        EXECUTE format('ALTER TABLE public.profiles DROP CONSTRAINT %I', cname);
    ELSE
        RAISE NOTICE 'No existing CHECK constraint found on profiles.role — nothing to drop.';
    END IF;
END;
$$;


-- ─────────────────────────────────────────────────────────────
-- 2. Add the replacement CHECK with the expanded role set
-- ─────────────────────────────────────────────────────────────
-- Named explicitly this time so future migrations can reference
-- it without discovery. Final allowed set:
--   'user'  — subscriber (default)
--   'admin' — operational staff, no financial visibility
--   'owner' — superset: admin + all financial data
--   'agent' — sales agent (existing value, untouched)

ALTER TABLE public.profiles
    ADD CONSTRAINT profiles_role_check
    CHECK (role IN ('user', 'admin', 'owner', 'agent'));

COMMENT ON COLUMN public.profiles.role IS
    'user = subscriber (default) | admin = operational staff, ZERO financial visibility | owner = admin superset + all financial data (reports, MRR/revenue, payment amounts, Razorpay IDs, commission) | agent = sales agent. Owner promotion is manual-only (see migration 006 bottom).';


-- ─────────────────────────────────────────────────────────────
-- 3. Verification query (run manually after applying)
-- ─────────────────────────────────────────────────────────────
-- SELECT conname, pg_get_constraintdef(oid)
--   FROM pg_constraint
--  WHERE conrelid = 'public.profiles'::regclass
--    AND contype  = 'c';
-- Expect: profiles_role_check | CHECK (role = ANY (ARRAY['user'::text, 'admin'::text, 'owner'::text, 'agent'::text]))


-- ═════════════════════════════════════════════════════════════
-- MANUAL STEP — DO NOT UNCOMMENT AS PART OF THIS MIGRATION
-- ═════════════════════════════════════════════════════════════
-- Owner promotion is a deliberate, audited, one-account action.
-- After this migration is applied, Chirayu runs this BY HAND in
-- the Supabase SQL editor, substituting his own phone number
-- (exactly as stored in profiles.phone, including country code):
--
-- UPDATE public.profiles
--    SET role       = 'owner',
--        updated_at = now()
--  WHERE phone = '+91XXXXXXXXXX';   -- ← Chirayu's phone
--
-- Verify afterwards:
-- SELECT id, full_name, phone, role FROM public.profiles WHERE role IN ('admin','owner');
-- ═════════════════════════════════════════════════════════════

-- ═════════════════════════════════════════════════════════════
-- END OF MIGRATION 20260801_006_owner_role_check
-- ═════════════════════════════════════════════════════════════
